# Generated by Django 3.0.7 on 2020-10-14 23:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spypp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevista',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spypp.Alumno'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='comentarios_comision_pps',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentarios de la Comisión de Pasantías'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spypp.Empresa'),
        ),
        migrations.AlterField(
            model_name='pasantia',
            name='comentarios_comision_pps',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentarios de la Comisión General de Pasantías'),
        ),
        migrations.AlterField(
            model_name='pasantia',
            name='comentarios_empresa',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentarios para la Comisión General de Pasantías'),
        ),
        migrations.AlterField(
            model_name='pasantia',
            name='entrevista',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrevista_pasantia', to='spypp.Entrevista'),
        ),
        migrations.AlterField(
            model_name='pasantia',
            name='tutor_docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spypp.Docente'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='fecha_inactivacion',
            field=models.DateField(default=datetime.datetime(2020, 10, 29, 20, 21, 52, 310157)),
        ),
    ]
