# Generated by Django 2.2.3 on 2019-11-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spypp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_fantasia',
            field=models.CharField(max_length=200, verbose_name='Nombre de Fantasía'),
        ),
        migrations.AlterField(
            model_name='pasantia',
            name='tutor_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spypp.TutorEmpresa'),
        ),
    ]
