# Generated by Django 2.2.3 on 2019-11-26 00:18

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields
import private_storage.fields
import private_storage.storage.files
import spypp.models


class Migration(migrations.Migration):

    dependencies = [
        ('spypp', '0002_auto_20191110_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='pasantia',
            name='practica_plan_de_estudio',
            field=models.BooleanField(default=False, verbose_name='Práctica del plan de estudio'),
        ),
        migrations.AddField(
            model_name='pasantia',
            name='status',
            field=models.CharField(choices=[('FINALIZADA', 'Finalizada'), ('DOCUMENTACION PENDIENTE', 'Documentación pendiente'), ('EN CURSO', 'En curso'), ('SIN INICIAR', 'Sin iniciar')], default='SIN INICIAR', max_length=23),
        ),
        migrations.AddField(
            model_name='puesto',
            name='fecha_inactivacion',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 21, 18, 4, 309598)),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='condicion_acreditacion',
            field=models.NullBooleanField(verbose_name='Está en condición de acreditación de práctica del plan de estudio?'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='expedicion_acreditacion',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Justificación de acreditación o su negativa'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='perfil',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=spypp.models.Alumno.perfil_upload_path, verbose_name='Foto de perfil'),
        ),
    ]
