# Generated by Django 2.2.3 on 2019-11-26 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spypp', '0003_auto_20191125_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='fecha_inactivacion',
            field=models.DateField(default=datetime.datetime(2019, 12, 10, 21, 20, 34, 251589)),
        ),
    ]
