# Generated by Django 2.2.3 on 2020-03-08 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spypp', '0004_auto_20191125_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='fecha_inactivacion',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 17, 21, 2, 387917)),
        ),
    ]
