# Generated by Django 2.1.5 on 2019-02-27 23:40

import alumno.models
import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('AL', 'Alumno'), ('CC', 'Comision Carrera'), ('CP', 'Comision PPS'), ('EM', 'Empresa')], default='AL', max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.PositiveIntegerField(unique=True, validators=[alumno.models.Alumno.validate_hash])),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='curriculums/')),
                ('descripcion_intereses', models.TextField(blank=True, max_length=500, null=True)),
                ('descripcion_habilidades', models.TextField(blank=True, max_length=1000, null=True)),
                ('ultima_actualizacion_perfil', models.DateField(default=datetime.date.today)),
                ('ultima_postulacion', models.DateField(blank=True, null=True)),
                ('condicion_acreditacion', models.NullBooleanField(verbose_name='Está en condición de acreditación')),
                ('expedicion_acreditacion', models.TextField(blank=True, max_length=500, null=True)),
                ('comentarios_comision_carrera', models.TextField(blank=True, max_length=1000, null=True)),
                ('comentarios_carrera_visibles', models.BooleanField(default=False, verbose_name='Comentarios visibles para las empresas')),
                ('comentarios_comision_pps', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('duracion', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='DirectorDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumno.Departamento')),
            ],
            options={
                'verbose_name': 'Director de Departamento',
                'verbose_name_plural': 'Directores de Departamento',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('numero_registro', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('box_oficina', models.CharField(max_length=30)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.Departamento')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=500)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('resultado', models.TextField(blank=True, max_length=1000, null=True)),
                ('comentarios_empresa', models.TextField(blank=True, max_length=1000, null=True)),
                ('comentarios_comision_pps', models.TextField(blank=True, max_length=1000, null=True)),
                ('notificado_alumno', models.BooleanField(default=False)),
                ('confirmada_alumno', models.BooleanField(default=False)),
                ('cancelada_empresa', models.BooleanField(default=False)),
                ('cancelada_alumno', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.Alumno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.Empresa')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
            },
        ),
        migrations.CreateModel(
            name='Pasantia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('logo', models.ImageField(upload_to='')),
                ('url', models.TextField(blank=True, max_length=300, null=True)),
                ('informe', models.FileField(blank=True, null=True, upload_to='informes/')),
                ('numero_legajo', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('comentarios_empresa', models.TextField(blank=True, max_length=1000, null=True)),
                ('comentarios_comision_pps', models.TextField(blank=True, max_length=1000, null=True)),
                ('entrevista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.Entrevista')),
                ('tutor_docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.Docente')),
            ],
            options={
                'verbose_name': 'Pasantia',
                'verbose_name_plural': 'Pasantias',
            },
        ),
        migrations.CreateModel(
            name='Postulaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
                ('entrevista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumno.Entrevista')),
            ],
            options={
                'verbose_name': 'Postulacion',
                'verbose_name_plural': 'Postulaciones',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('puesto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=1000)),
                ('dedicacion', models.PositiveSmallIntegerField()),
                ('horario', models.CharField(max_length=20)),
                ('remuneracion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Empresa')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='SubcomisionCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumno.Carrera')),
                ('docente', models.ManyToManyField(to='alumno.Docente', verbose_name='docentes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrera_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SubcomisionCarrera',
                'verbose_name_plural': 'SubcomisionesCarreras',
            },
        ),
        migrations.CreateModel(
            name='SubcomisionPasantiasPPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumno.Departamento')),
                ('docente', models.ManyToManyField(to='alumno.Docente', verbose_name='docentes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pps_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SubcomisionPasantiasPPS',
                'verbose_name_plural': 'SubcomisionesPasantiasPPS',
            },
        ),
        migrations.CreateModel(
            name='TutorEmpresa',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.Empresa')),
            ],
            options={
                'verbose_name': 'Tutor de Empresa',
                'verbose_name_plural': 'Tutores de Empresas',
            },
        ),
        migrations.AddField(
            model_name='postulaciones',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Puesto'),
        ),
        migrations.AddField(
            model_name='pasantia',
            name='tutor_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.TutorEmpresa'),
        ),
        migrations.AddField(
            model_name='directordepartamento',
            name='docente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumno.Docente'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Departamento'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.Carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postulaciones',
            unique_together={('puesto', 'alumno')},
        ),
        migrations.AlterUniqueTogether(
            name='entrevista',
            unique_together={('alumno', 'empresa', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='directordepartamento',
            unique_together={('departamento', 'docente')},
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together={('departamento', 'nombre')},
        ),
    ]
