# Generated by Django 2.1 on 2018-09-05 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('numero_registro', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('curriculum', models.FileField(upload_to='curriculums/')),
                ('descripcion_intereses', models.TextField(max_length=500)),
                ('descripcion_habilidades', models.TextField(max_length=1000)),
                ('ultima_actualizacion_perfil', models.DateTimeField()),
                ('ultima_postulacion', models.DateTimeField()),
                ('ultimo_ingreso', models.DateTimeField()),
                ('primer_ingreso', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('prioridad', models.PositiveSmallIntegerField()),
                ('condicion_acreditacion', models.NullBooleanField()),
                ('expedicion_acreditacion', models.TextField(max_length=500)),
                ('comentarios_comision_carrera', models.TextField(max_length=1000)),
                ('comentarios_carrera_visibles', models.BooleanField()),
                ('comentarios_comision_pps', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('numero_registro', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('box_oficina', models.CharField(max_length=30)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=500)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('resultado', models.TextField(max_length=1000)),
                ('comentarios_empresa', models.TextField(max_length=1000)),
                ('comentarios_comision_pps', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Postulaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('puesto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=1000)),
                ('dedicacion', models.PositiveSmallIntegerField()),
                ('horario', models.CharField(max_length=20)),
                ('remuneracion', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SubcomisionCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Carrera')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='SubcomisionPasantiasPPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Departamento')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='SuperUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TutorEmpresa',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Pasantia',
            fields=[
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('entrevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='alumno.Entrevista')),
                ('informe', models.FileField(upload_to='informes/')),
                ('numero_legajo', models.PositiveIntegerField(null=True, unique=True)),
                ('comentarios_empresa', models.TextField(max_length=1000)),
                ('comentarios_comision_pps', models.TextField(max_length=1000)),
                ('tutor_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Docente')),
                ('tutor_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.TutorEmpresa')),
            ],
        ),
        migrations.AddField(
            model_name='entrevista',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno'),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Empresa'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='super_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.SuperUsuario'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Departamento'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='super_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.SuperUsuario'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Carrera'),
        ),
        migrations.AlterUniqueTogether(
            name='subcomisionpasantiaspps',
            unique_together={('departamento', 'docente')},
        ),
        migrations.AlterUniqueTogether(
            name='subcomisioncarrera',
            unique_together={('carrera', 'docente')},
        ),
        migrations.AlterUniqueTogether(
            name='postulaciones',
            unique_together={('empresa', 'alumno')},
        ),
        migrations.AlterUniqueTogether(
            name='entrevista',
            unique_together={('alumno', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='empresa',
            unique_together={('nombre', 'departamento')},
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together={('departamento', 'nombre')},
        ),
    ]
