# Generated by Django 2.2.1 on 2019-08-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
