# Generated by Django 2.1.5 on 2019-02-27 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='duracion',
        ),
    ]
