# Generated by Django 2.1.5 on 2019-02-03 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='entrevista',
            name='cancelada_alumno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='cancelada_empresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='comentarios_carrera_visibles',
            field=models.BooleanField(default=False, verbose_name='Comentarios visibles para las empresas'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='condicion_acreditacion',
            field=models.NullBooleanField(verbose_name='Está en condición de acreditación'),
        ),
        migrations.AlterField(
            model_name='pasantia',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pasantia',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pasantia',
            name='tutor_docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.Docente'),
        ),
        migrations.AlterField(
            model_name='pasantia',
            name='tutor_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.TutorEmpresa'),
        ),
        migrations.AlterField(
            model_name='subcomisioncarrera',
            name='docente',
            field=models.ManyToManyField(to='alumno.Docente', verbose_name='docentes'),
        ),
        migrations.AlterField(
            model_name='subcomisionpasantiaspps',
            name='docente',
            field=models.ManyToManyField(to='alumno.Docente', verbose_name='docentes'),
        ),
        migrations.RemoveField(
            model_name='entrevista',
            name='notificado_empresa',
        ),
        migrations.AlterUniqueTogether(
            name='entrevista',
            unique_together={('alumno', 'empresa', 'fecha')},
        ),
    ]
