# Generated by Django 2.1 on 2018-10-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='directordepartamento',
            options={'verbose_name': 'Director de Departamento', 'verbose_name_plural': 'Directores de Departamento'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='entrevista',
            options={'verbose_name': 'Entrevista', 'verbose_name_plural': 'Entrevistas'},
        ),
        migrations.AlterModelOptions(
            name='pasantia',
            options={'verbose_name': 'Pasantia', 'verbose_name_plural': 'Pasantias'},
        ),
        migrations.AlterModelOptions(
            name='postulaciones',
            options={'verbose_name': 'Postulacion', 'verbose_name_plural': 'Postulaciones'},
        ),
        migrations.AlterModelOptions(
            name='puesto',
            options={'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
        migrations.AlterModelOptions(
            name='subcomisioncarrera',
            options={'verbose_name': 'SubcomisionCarrera', 'verbose_name_plural': 'SubcomisionesCarreras'},
        ),
        migrations.AlterModelOptions(
            name='subcomisionpasantiaspps',
            options={'verbose_name': 'SubcomisionPasantiasPPS', 'verbose_name_plural': 'SubcomisionesPasantiasPPS'},
        ),
        migrations.AlterModelOptions(
            name='tutorempresa',
            options={'verbose_name': 'Tutor de Empresa', 'verbose_name_plural': 'Tutores de Empresas'},
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='primer_ingreso',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='ultimo_ingreso',
        ),
        migrations.RemoveField(
            model_name='subcomisioncarrera',
            name='docente',
        ),
        migrations.AddField(
            model_name='subcomisioncarrera',
            name='docente',
            field=models.ManyToManyField(to='alumno.Docente'),
        ),
    ]
