# Generated by Django 2.1.5 on 2019-03-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
