# Generated by Django 2.2.3 on 2019-08-21 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasantia',
            name='entrevista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrevista_pasantia', to='alumno.Entrevista', unique=True),
        ),
    ]
