# Generated by Django 2.1 on 2018-11-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20181119_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevista',
            name='cancelada_alumno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='cancelada_empresa',
            field=models.BooleanField(default=False),
        ),
    ]
