# Generated by Django 2.1.5 on 2019-03-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20190305_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
