# Generated by Django 2.1 on 2018-10-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20181021_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='tipo',
        ),
    ]
