# Generated by Django 2.1 on 2018-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20180916_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='comentarios_comision_carrera',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='comentarios_comision_pps',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculums/'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='descripcion_habilidades',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='descripcion_intereses',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='expedicion_acreditacion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ultima_postulacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
