# Generated by Django 2.1 on 2018-10-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20181014_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomisionpasantiaspps',
            name='docente',
        ),
        migrations.AddField(
            model_name='subcomisionpasantiaspps',
            name='docente',
            field=models.ManyToManyField(to='alumno.Docente'),
        ),
    ]
