# Generated by Django 2.1 on 2018-10-28 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_auto_20181021_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcomisioncarrera',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrera_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcomisionpasantiaspps',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pps_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
