# Generated by Django 2.1 on 2018-12-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_auto_20181125_1828'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entrevista',
            unique_together={('alumno', 'empresa', 'fecha')},
        ),
    ]
