# Generated by Django 2.1 on 2018-10-14 22:16

import alumno.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_auto_20181014_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='numero_registro',
            field=models.PositiveIntegerField(unique=True, validators=[alumno.models.Alumno.validate_hash]),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='comentarios_comision_pps',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='comentarios_empresa',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='resultado',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='remuneracion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
