# Generated by Django 2.1 on 2019-03-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_auto_20190324_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrevista',
            name='aceptado_para_pasantia',
        ),
    ]
