# Generated by Django 2.1.5 on 2019-03-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_auto_20190305_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puesto',
            old_name='rentada',
            new_name='rentado',
        ),
    ]
