# Generated by Django 2.1.5 on 2019-03-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_auto_20190305_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
