# Generated by Django 2.1 on 2018-12-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_auto_20181202_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrevista',
            name='notificado_empresa',
        ),
        migrations.AlterField(
            model_name='pasantia',
            name='tutor_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.TutorEmpresa'),
        ),
    ]
