# Generated by Django 2.1 on 2018-09-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_auto_20180916_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.Carrera'),
        ),
    ]
