# Generated by Django 2.1 on 2019-03-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_remove_entrevista_aceptado_para_pasantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevista',
            name='confirmada_alumno',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
