# Generated by Django 2.1 on 2018-11-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0005_auto_20181101_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
