# Generated by Django 2.1 on 2019-03-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0005_entrevista_confirmada_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrevista',
            name='confirmada_alumno',
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='status',
            field=models.CharField(choices=[('COA', 'Confirmada Alumno'), ('NOC', 'No Confirmada Alumno'), ('NOA', 'Notificada Alumno'), ('CAA', 'Cancelada Alumno'), ('REA', 'Realizada'), ('CAE', 'Cancelada Empresa')], default='NOA', max_length=3),
        ),
    ]
