# Generated by Django 2.1 on 2019-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0006_auto_20190324_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='empresa',
            unique_together={('departamento', 'nombre_fantasia')},
        ),
    ]
