# Generated by Django 2.1 on 2019-03-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0007_auto_20190324_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre_fantasia',
            field=models.CharField(max_length=200),
        ),
    ]
