# Generated by Django 2.1 on 2018-11-04 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0008_auto_20181104_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcomisioncarrera',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Carrera', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcomisionpasantiaspps',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Pps', to=settings.AUTH_USER_MODEL),
        ),
    ]
