# Generated by Django 2.1 on 2018-11-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0009_auto_20181104_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=1, unique=True),
        ),
    ]
