# Generated by Django 2.1 on 2019-03-25 23:35

import alumno.models
from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0009_alumno_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='historia_academica',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=alumno.models.Alumno.historia_upload_path, verbose_name='Historia Académica (.pdf)'),
        ),
    ]
