# Generated by Django 2.1 on 2019-03-31 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0010_alumno_historia_academica'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='entrevista',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrevista_postulacion', to='alumno.Entrevista'),
        ),
    ]
