# Generated by Django 2.1 on 2018-11-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0010_auto_20181104_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
