# Generated by Django 2.1 on 2019-03-31 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0011_auto_20190331_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.Alumno'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='alumno.Puesto'),
        ),
    ]
