# Generated by Django 2.1 on 2019-03-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0012_auto_20190331_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='entrevista',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='entrevista',
            field=models.ManyToManyField(blank=True, null=True, related_name='entrevista_postulacion', to='alumno.Entrevista'),
        ),
    ]
