# Generated by Django 2.2 on 2019-04-21 20:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0014_auto_20190331_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='mail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='fecha_desestimacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='entrevista',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevista_postulacion', to='alumno.Entrevista'),
        ),
        migrations.AlterField(
            model_name='subcomisioncarrera',
            name='carrera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrera_comision', to='alumno.Carrera'),
        ),
        migrations.AlterField(
            model_name='subcomisioncarrera',
            name='docente',
            field=models.ManyToManyField(related_name='comision_docente', to='alumno.Docente', verbose_name='docentes'),
        ),
    ]
