# Generated by Django 2.1 on 2019-03-31 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0014_auto_20190331_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='mail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='entrevista',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrevista_postulacion', to='alumno.Entrevista'),
        ),
        migrations.AlterField(
            model_name='subcomisioncarrera',
            name='carrera',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrera_comision', to='alumno.Carrera'),
        ),
    ]
