# Generated by Django 2.1 on 2019-06-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0015_auto_20190421_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='puesto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='comentarios_comision_pps',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentarios de la Comisión de Pasantías'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='comentarios_empresa',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentarios para la Comisión de Pasantías'),
        ),
        migrations.AlterField(
            model_name='pasantia',
            name='comentarios_comision_pps',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentarios de la Comisión de Pasantías'),
        ),
        migrations.AlterField(
            model_name='pasantia',
            name='comentarios_empresa',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comentarios para la Comisión de Pasantías'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='fecha_desestimacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
