# Generated by Django 2.1 on 2019-06-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0016_auto_20190617_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='horario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.CharField(choices=[('BE', 'Back-end'), ('FE', 'Front-end'), ('QA', 'Quality Assurance'), ('MB', 'Mobile - iOS'), ('AND', 'Mobile - Android'), ('IND', 'Indistinto'), ('OTR', 'Otro')], default='IND', max_length=3, verbose_name='Área'),
        ),
    ]
