# Generated by Django 2.1 on 2019-06-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0018_auto_20190617_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasantia',
            name='entrevista',
        ),
        migrations.AddField(
            model_name='entrevista',
            name='pasantia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrevista_pasantia', to='alumno.Pasantia'),
        ),
    ]
