# Generated by Django 2.1 on 2019-06-17 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0019_auto_20190617_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrevista',
            name='pasantia',
        ),
        migrations.AddField(
            model_name='pasantia',
            name='entrevista',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrevista_pasantia', to='alumno.Entrevista'),
            preserve_default=False,
        ),
    ]
