# Generated by Django 2.1 on 2019-06-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0021_auto_20190617_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasantia',
            name='entrevista',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entrevista_pasantia', to='alumno.Entrevista'),
        ),
    ]
