# Generated by Django 2.1 on 2019-06-20 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0023_auto_20190617_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='progreso',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
