# Generated by Django 2.1 on 2019-07-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0025_auto_20190709_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcomisionpasantiaspps',
            old_name='docente',
            new_name='docentes',
        ),
    ]
